# -*- coding: utf-8 -*-
"""Copy of Copy of Sample EDA Submission Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHOQBKTv9IM8zJunioJo5Hbuvt-jAZHQ

# **Project Name**    -

##### **Project Type**    -Global Terrorism EDA
##### **Done By**    - Nalini Ranjan

# **Project Summary -**

The Global terrorism database(GTD) is an open-source database including info on terrorist attack from 1970-2017.
It has systemic data on domestic as well as international terrorist incidents and have more than 180000 attack.
This data is maintained by researchers at the National consortium for the study of terrorism and responses to terrorism (START).
Different key findings:
It gives the date of attack, country affected, regions of attack , city, attack type and target bodies, gang causing , weapons used, details how weapons have been used.
In this project we have used NumPy, Pandas , seaborn ,Matplotlib, plotty graph by importing them with their respective alias.
The entire data consist of 181691. Rows and 135 columns.
From the data we extracted the total no. Of attacks per year.
As per data 2014 has maximum no. Of terrorist attack.
We have extracted the kills per year I.e deaths due to terrorist attack and plotted bar chart for the same.
We have also classified the attack of top 10 gang/group causing maximum no. Of attacks and plotted the pyplot for the same.
In addition to it we also find out the deaths caused from each group or gang.
Among these we have divided the attack as attack was successful or suicidal.
We have extracted the casualties in each region and also divided them in city, Baghdad was the most targeted city in the world.
We have extracted the data of top attack plan and guerrilla action scores highest of 80.69%
Iraq was the country that suffered the highest no. Of terror attack since 1970 followed by Pakistan, Afghanistan, India etc.
Now, we have extracted the no. Of terror attacks suffered by India from 1970-2017 and highest in India was in 2016 and Srinagar has highest no of attacks which caused a highest loss of lives.
We have also identified the weapons type and death and cause.
These can help us to spy out the weapons and destroy them and prevent future terror attack.

# **Problem Statement**

To understand the scope, causes, and impacts of terrorism worldwide, and to develop strategies to mitigate its negative effects and prevent its spread."

This statement encapsulates the need to study terrorism in a comprehensive and systemic manner, taking into account its various forms, drivers, and consequences. The goal is to find ways to reduce its occurrence and minimize the harm it causes to individuals, communities, and societies. The problem statement highlights the importance of interdisciplinary research and collaboration in addressing terrorism, as it involves a complex array of social, political, economic, and psychological factors.

#### **Define Your Business Objective?**

The main business objective for addressing global terrorism is to minimize risks and negative impacts to the company and its stakeholders. This can include the following objectives:

Ensuring the safety and security of employees, customers, assets, and operations.
Minimizing the likelihood of a terrorism-related incident occurring.
Minimizing the impact if an incident does occur.
Complying with local and international regulations and standards related to terrorism.
Protecting the company's reputation and brand image.
Maintaining continuity of operations and minimizing disruptions to the business.
Building and maintaining relationships with key stakeholders, including governments, customers, and communities.
Contributing to efforts to create a safer and more secure global environment.
These objectives reflect the need for companies to be proactive in addressing the risks associated with terrorism, while balancing the need to continue operating in an increasingly complex and uncertain global environment.

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# Import Libraries
#Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import folium as fo
import plotly.graph_objects as go
# %matplotlib inline
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

"""### Dataset Loading"""

# Load Dataset
from google.colab import drive
drive.mount('/content/drive')

file_path ='/content/drive/MyDrive/Global Terrorism Data.csv'
df=pd.read_csv(file_path,encoding_errors='ignore')

"""### Dataset First View"""

# Dataset First Look
df.head(10)

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
df.shape

"""### Dataset Information"""

# Dataset Info
df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
print(df.duplicated().sum())

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
nan_count = df.isna().sum(axis = 0)
nan_count.head(10)

# Visualizing the missing values
nan_count.plot(kind='bar',figsize=(25,8))
plt.title('Null Value',fontsize=20)
plt.xlabel('colums',fontsize=20)
plt.ylabel('null values',fontsize=20)
plt.show

"""### What did you know about your dataset?

The Global Terrorism Database is a  database of terrorism attacks and incidents that have occurred around the world since 1970 to 2017. It includes information on over 180,000 incidents, including details on the date and location of the attack, the weapons used, the target, the group responsible, and the number of casualties.

It is a valuable resource to find the patterns and trends of terrorism around the world. By analyzing this data, one can gain insights into the motivations, tactics, and targets of terrorist groups, as well as the effectiveness of counter-terrorism measures. Additionally, the data can be used to inform security planning and allocate resources more effectively.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df.columns

# Dataset Describe
df.describe()

"""### Check Unique Values for each variable."""

# Check Unique Values for each variable.
column_list = df.columns.values.tolist()
no_unique=[]
for column_name in column_list:
  no_unique.append(df[column_name].nunique())
unique = pd.DataFrame(list(zip(column_list, no_unique)),
               columns =['variable', 'no. of uniques values'])
unique.head(10)

"""## ***3. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Total number of attack
total_no_of_attacks=df.iyear.count()
print('Total no. of attacks',total_no_of_attacks)

# Chart - 1 visualization code

#1 Number of attacks per year

attacks_per_year=df.groupby('iyear').agg({'iyear':'count'})
attacks_per_year.rename(columns={'iyear':'attacks'},inplace=True)
attacks_per_year.index.names = ['year']
attacks_per_year.head(10)

#Graph

attacks_per_year.plot(kind='bar', figsize=(20,8))
plt.title('Terrorist Attacks Worldwide by Year 1970-2017',fontsize=20)
plt.xlabel('Year',fontsize=20)
plt.ylabel('No. of attacks',fontsize=20)
plt.show

"""##### 1. Why did you pick the specific chart?

As bar graph is helpful in summarizeing large data set in visual form and we can estimate key values at a glance.

##### 2. What is/are the insight(s) found from the chart?

The chart is plotted total no. Of attacks vs year; it gives the total no. Of attacks each year from 1997-2017.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, as the data gives the history of attacks, Here we can see clearly that the no. of attacks have increased in 2007-2017 and 2014 was the most active year for the terrorists.
This insight will help us to understand the patterns of year which has highest no. Of attacks and learn from the past to prevent in future.

#### Chart - 2
"""

# Chart - 2 visualization code

#Total number of kills per year

kills_per_year=df.groupby('iyear').agg({'nkill':'sum'})
kills_per_year.rename(columns={'nkill':'deaths'},inplace=True)
kills_per_year.index.names = ['year']
kills_per_year.head(15)

#Graph

kills_per_year.plot(kind='bar', figsize=(20,8))
plt.title('Deaths in Terrorist Attacks Worldwide by Year 1970-2017',fontsize=20)
plt.xlabel('Year',fontsize=20)
plt.ylabel('Deaths',fontsize=20)
plt.show

"""##### 1. Why did you pick the specific chart?

As bar chart show each data category in a frequency distribution, and permit a visual check of the accuracy and reasonableness of calculation it clearly provides the data.

##### 2. What is/are the insight(s) found from the chart?

Bar chart is plotted on no. Of kills i.e deaths vs year; it gives the man resource loss per year due to attacks.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, as the data gives the number of kills, Here we can see clearly that the no. of attacks is directly proportional to no of kills such as where no of attacks is more then no of deaths is also increased and 2014 was the most active year for the terrorists..

#### Chart - 3
"""

# Chart - 3 visualization code

#Number of attacks done by different groups
7
attacks_group=df.groupby('gname').agg({'iyear':'count'})
attacks_group.sort_values(by='iyear',ascending=False,inplace=True)
attacks_group.rename(columns={'iyear':'total attack'},inplace=True)
attacks_group.index.names = ['Group name']
attacks_group.head(10)
Top_ten_groups=attacks_group.head(10)
Top_ten_groups


#Graph
plt.figure(figsize=(8, 8))

data=Top_ten_groups['total attack']
key= Top_ten_groups.index
explode = [0.1, 0.5, 0.5, 0.5, 0.5,0.5,0.5,0.5,0.5,0.5]
plt.pie(data, labels=key,explode=explode,autopct='%1.2f%%')
plt.show

"""##### 1. Why did you pick the specific chart?

As pie chart helps to organize and show data as a percentage of a whole.

##### 2. What is/are the insight(s) found from the chart?

Pie chart is plotted on total number of attacks done by different groups it gives total percentage of attacks done by groups.
Here we clearly see that most of the attacks were executed by unknown group or we can say these attacks were unclaimed by any group and after that Taliban is the most active group out of others which did around 6.5% of total attacks and ISIL is after them.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, the data we are getting here is about the most active terror group. So by using these data any agencies will be able to highlight those groups and track them by making them priorities.

#### Chart - 4
"""

# Chart - 4 visualization code

# successful and suicide attacks done per year 

succ_attack=df.groupby('iyear').agg({'iyear':'count'})
succ_attack['Successful attack']=df.groupby('iyear').agg({'success':'sum'})
succ_attack['Suicide attack']=df.groupby('iyear').agg({'suicide':'sum'})
succ_attack.rename(columns={'iyear':'Total attacks'},inplace=True)
succ_attack.head(5)


#Graph

succ_attack.plot(kind='line',figsize=(20,8),grid=True)
plt.show

"""##### 1. Why did you pick the specific chart?

Here we used line graph to track changes over short and long periods of time. When smaller changes exist, line graphs are better to use than bar graphs.

##### 2. What is/are the insight(s) found from the chart?

Line graph is plotted on Total attacks , Successful attacks & Suicide attacks.it gives the total no. of successful & suicide attacks over a certain time period. The line graph shows that the no. of total attacks and successful attacks risen over years but suicide bombers kind of attacks are either constant or got minimum hike.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, Here these line graphs clearly shows that both no. of attacks and successful attacks are proportional where suicide rate are not much over the years. So for the agencies it will be quite helpful to raise alerts for the peoples for any other future hits.

#### Chart - 5
"""

# Chart - 5 visualization code

# total no of kills done by groups 

total_kills = df.groupby(['gname'])[['nkill']].agg('sum').sort_values(by='nkill', ascending=False)
total_kills.reset_index(inplace=True)
total_kills

# Graph

sns.barplot(y = total_kills['gname'][1:16], x= total_kills['nkill'][1:16], palette=('inferno'))
plt.xticks(rotation=90)
fig = plt.gcf()
fig.set_size_inches(10,6)
plt.title('Terrorist Groups who caused most number of Casualties')
plt.show()

"""##### 1. Why did you pick the specific chart?

Here we used horizontal barchart so it enables you to display those values in a natural way.

##### 2. What is/are the insight(s) found from the chart?

Bar chart is plotted on terrorist groups vs casualities done by them ; it gives the no. of casualities done by different terrorist groups. As in data we can see that around 39000 casualty done by ISIL which is highest in figure.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

This horizontal bar graph tells us about the most dangerous terrorist group all over the world, and ISIL, Taliban and Boko Haram tops the table. This data creates a big positive business impact for any agencies who were tracking them. This data will help agencies to focus on some specific groups.

#### Chart - 6   Pair Plot
"""

# Chart - 6 visualization code

# percentage of kills in each regions

total_casualities_con = df.groupby(['region'])['nkill'].sum().reset_index()
total_casualities_con['%per'] = (total_casualities_con['nkill']/total_casualities_con['nkill'].sum())*100
total_casualities_con

# Graph

sns.pairplot(total_casualities_con, diag_kind="kde",height=3,aspect=2)
plt.show

"""##### 1. Why did you pick the specific chart?

As pairs plot allows us to see both distribution of single variables and relationships between two variables.

##### 2. What is/are the insight(s) found from the chart?

The visualization provides information on the total number of casualties and the percentage of casualties per region, and it is clear that this information can be applied to create a positive business impact.
There is a positive correlation between the percentage of deaths caused by terrorism in different regions, as shown by the upward trend in the scatter plots. However, the correlation is not strong, as there is still a lot of scatter in the data points.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

This graph can be used to find insights for an intelligence agency in terms of understanding the regions where the highest number of casualties are occurring. If the agency can identify regions with high casualties, it can take appropriate measures to reduce the casualties and prevent future attacks. The graph can also help the agency to understand if there is any pattern or trend in the distribution of casualties across the regions. Based on the insights gained from the graph, the agency can take appropriate actions to counter terrorism and prevent further casualties.

#### Chart - 7
"""

# Chart - 7 visualization code

# total casualitites in cities

total_casualities_city = df['city'].value_counts().reset_index().rename(columns={'index':'city','city':'Count'})

#Graph
sns.barplot(y = total_casualities_city['city'][1:16], x= total_casualities_city['Count'][1:16], palette=('inferno'))
plt.xticks(rotation=90)
fig = plt.gcf()
fig.set_size_inches(15,10)
plt.title('Most Targeted City in the world by Terrorism')
plt.show()

"""##### 1. Why did you pick the specific chart?

Here we used horizontal barchart so it enables you to display those values in a natural way.

##### 2. What is/are the insight(s) found from the chart?

Bar chart is plotted on most targeted cities vs causalities; it gives the no. of causalities done in several cities and Baghdad tops the table with around more than 7000 casualties.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The bar plot provides a visual representation of the data, which can be useful in identifying trends and patterns in the data. For example, it can help to highlight which cities have been the most frequently targeted by terrorists, and can provide a basis for further analysis and investigation into the causes of terrorism in those cities.

#### Chart - 8
"""

# Chart - 8 visualization code

#9 top attack plans

top_attack_plan = df['alternative_txt'].value_counts().reset_index().rename(columns={'index':'alternative_txt','alternative_txt':'Count'})
top_attack_plan

#Graph

data=top_attack_plan['Count']
keys= top_attack_plan['alternative_txt']
explode = [0.0,0.1,0.2,0.4,0.6]
palette_color = sns.color_palette('bright')
plt.figure(figsize=(8, 8))
plt.pie(data, labels=keys,colors=palette_color,explode=explode,autopct='%1.2f%%')
plt.show

"""##### 1. Why did you pick the specific chart?

Here we used pie chart because it helps to organize and show data as a percentage of a whole.

##### 2. What is/are the insight(s) found from the chart?

The above data provides the insights into the distribution of the various types of terrorist attacks based on the "alternative_txt" column of the data. The data is visualized as a pie chart, where the size of each wedge of the pie represents the proportion of the total number of attacks that fall under that particular type of attack. The values are also represented as percentages on the chart, which provides a more interpretable representation of the data.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The insights from this visualization can help the agencies in understanding the types of attacks that are most common in the data, and can potentially inform counter-terrorism strategies and efforts.

#### Chart - 9
"""

# Chart - 9 visualization code

# Number of attacks in per region

region_wise=df.groupby('region_txt').agg({'iyear':'count'}).rename(columns={'iyear':'total_attacks'}).reset_index().sort_values('total_attacks',ascending=False)
region_wise.head(10)

#Graph

plt.rcParams['figure.figsize']=(15,8)
sns.set_style("darkgrid")
sns.set(font_scale=1.2)
f=sns.barplot(x='total_attacks',y='region_txt',data=region_wise,palette='mako')
f.set_title("Region Wise Global Terrorist Attack   Year 1970-2017",fontsize=25,fontweight='bold')
f.set_xlabel('Total Attacks',fontsize=20)
f.set_ylabel('Region',fontsize=20)

"""##### 1. Why did you pick the specific chart?

Here we used horizontal barchart so it enables you to display those values in a natural way.

##### 2. What is/are the insight(s) found from the chart?

It provides an insight into which regions have experienced the most terrorist attacks and helps to identify the regions that are most vulnerable to these types of incidents. We can clearly see that Middle East and North Africa is highly affected by thses attacks.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The data can be useful in developing strategies to prevent and respond to terrorist attacks in these regions, which can have a positive impact on businesses operating in these areas.

#### Chart - 10
"""

# Chart - 10 visualization code

#Countries that suffered the most number of Terror attacks/Hostile situations since 1970

most_attacked_countries = df.groupby(['country_txt'])['country_txt'].size().reset_index(name='No_of_Incidents')
most_attacked_countries.sort_values(by=['No_of_Incidents'], ascending = False, inplace = True)
most_attacked_countries.set_index('country_txt', inplace=True)
most_attacked_countries.index.name = 'country'

most_attacked_countries.head(15)

#Graph


fig = px.choropleth(most_attacked_countries, locations=most_attacked_countries.index, 
                    locationmode='country names', color='No_of_Incidents', 
                    color_continuous_scale='reds', hover_name=most_attacked_countries.index, 
                    hover_data={'No_of_Incidents': ':,d'})
fig.update_layout(title_text='Countries with the Most Terrorist Attacks')
fig.update_layout(geo=dict(showframe=False, showcoastlines=False, projection_type='equirectangular'))
fig.show()

"""##### 1. Why did you pick the specific chart?

It seems to be a choropleth map created using Plotly Express. It is a useful way to visualize the data when you want to show how a numeric value is distributed across geographical locations.

##### 2. What is/are the insight(s) found from the chart?

The insight found from this chart is that the countries with the most number of terrorist attacks can be seen by the color intensity on the map. The darker the color, the higher the number of incidents, which indicates that the country is more prone to terrorist attacks. In this case, Iraq, Afghanistan, and India have the highest number of terrorist attacks.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The information on the countries with the most terrorist attacks can help companies make informed decisions regarding investment, business operations, and risk management in those countries, whereas agengies like RAW get the help to find those terrorist groups.

#### Chart - 11
"""

# Chart - 11 visualization code

#Terror incidents suffered by India since 1970

data_India = df.loc[df.country_txt == 'India']
data_India.tail(15)

#Graph

plt.subplots(figsize=(18,6))
sns.countplot('iyear',data= data_India, palette='icefire', edgecolor = sns.dark_palette("Black"))
plt.xticks(rotation = 90)
plt.title('Number of terror incidents suffered by India (1970-2017)')
plt.show()

"""##### 1. Why did you pick the specific chart?

As bar chart show each data category in a frequency distribution, and permit a visual check of the accuracy and reasonableness of calculation it clearly provides the data.

##### 2. What is/are the insight(s) found from the chart?

Bar chart is plotted on no. Of terror incident in India vs year; it gives the no. of attacks happened in India from year (1970-2017). The insight from the chart is that there has been a significant increase in the number of terror incidents in India over the years, particularly after the year 2000.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The government or relevant agencies use this data to address the root causes of terrorism and implement effective counter-terrorism measures, it could potentially have a positive impact on the overall security and stability of the country, which could in turn have a positive impact on business and economic activities.

#### Chart - 12
"""

# Chart - 12 visualization code

# Casuality in india per year

casulities_India = data_India.groupby(['iyear'])[['nkill','nwound','nkillter']].sum()
casulities_India.reset_index(inplace=True)
casulities_India

#Graph

casulities_India.set_index('iyear').plot(figsize=(20,8),grid = True)
plt.show()

"""##### 1. Why did you pick the specific chart?

Here we used line graph to track changes over short and long periods of time. When smaller changes exist, line graphs are better to use than bar graphs.

##### 2. What is/are the insight(s) found from the chart?

Line graph is plotted on no. of kill ,no. of wound &no. of terrorist killed .it gives the total no. of people killed , wounded & terrorist killed in India from (1970-2017). This chart could help understand the historical trend of casualties caused by terrorism in India.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, as the data gives the history of attacks, Here we can see clearly that the no. of attacks have increased around 1990-2010 and 2008 was the most active year for the terrorists.
This insight will help us to understand the patterns of year which has highest no. Of attacks and learn from the past to prevent in future.

#### Chart - 13
"""

# Chart - 13 visualization code

#Number of Attacks & Causalities by City since 1970

attack_loc = data_India['city'].value_counts().reset_index().rename(columns={'index':'city','city':'No_of_Attacks'})
death_count = data_India.groupby(['city'])['nkill'].sum().reset_index()

death_count_per_loc = attack_loc.merge(death_count, how='inner', on='city')
death_count_per_loc[:10]

#Graph
death_count_per_loc = death_count_per_loc.sort_values('No_of_Attacks', ascending=False)[:15]

# Plot lines for number of attacks and number of kills
plt.figure(figsize=(20, 10))
plt.plot(death_count_per_loc['city'], death_count_per_loc['No_of_Attacks'], color='blue', label='Number of Attacks')
plt.plot(death_count_per_loc['city'], death_count_per_loc['nkill'], color='red', label='Number of Kills')

# Set axis labels and title
plt.xlabel('City')
plt.ylabel('Count')
plt.title('Terrorist Attacks and Number of Kills in Top 15 Indian Cities')

"""##### 1. Why did you pick the specific chart?

Here we used line graph , as it is commonly drawn to show information that is continous and changes over time.

##### 2. What is/are the insight(s) found from the chart?

This line chart is plotted no of attacks and s casualties vs cities, this data depicts that Srinagar has highest casualties bijapur has lowest casualties

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

This data will help to keep identify the city which is most impacted and keep a survilence on this cities and close proximities and find out the cause and keep an eye on major gang of this cities and prevent future attacks.

#### Chart - 14
"""

# Chart - 14 visualization code

# Exploring the most attacked City in India i.e Srinagar excluding unknown attack which is 53% of total attack

srinagar_data = data_India.loc[data_India.city == 'Srinagar']
srinagar_terror_log = srinagar_data['gname'].value_counts().reset_index().rename(columns={'index': 'Terrorist Group', 'gname': 'No. of Attacks'})
srinagar_terror_log.set_index('Terrorist Group', inplace=True)


#Graph
top_10_group_srinagar=srinagar_terror_log[1:11]
fig = px.pie(top_10_group_srinagar, values='No. of Attacks', names=top_10_group_srinagar.index, hole=.3)
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.update_layout(title_text='Terrorist Groups Operating in Srinagar')
fig.show()

"""##### 1. Why did you pick the specific chart?

A pie chart was chosen to visualize the distribution of the number of attacks carried out by different terrorist groups in the city of Srinagar.This type of chart is particularly useful when the data is categorical in nature and one wants to show the relative proportions of each category.

##### 2. What is/are the insight(s) found from the chart?

The insight we get are the proportion of different terrorist groups that have carried out attacks in Srinagar, India. The data in the chart helps to understand which groups are most active in the city and could inform security measures and counter-terrorism strategies.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The gained insights might help in creating a positive business impact for the government and agencies like RAW by providing them with information on the most active terrorist groups in Srinagar and their frequency of attacks. This information can be used to formulate effective counter-terrorism strategies and allocate resources accordingly. However, the impact can only be determined by the government and agencies' ability to effectively utilize the information and take appropriate actions.

#### Chart - 15
"""

# Chart - 15 visualization code

# kill vs weapons type(India)

killvswtype=data_India.groupby(['weaptype1_txt']).agg({'nkill':'sum'})
killvswtype.rename(columns={'nkill':'Deaths'},inplace=True)
killvswtype.index.names = ['Weapon Type']
killvswtype


#Graph

killvswtype.plot(kind='bar')
plt.xlabel('Weapon Type',fontsize=20)
plt.ylabel('Deaths',fontsize=20)
plt.show

"""##### 1. Why did you pick the specific chart?

As bar graph is helpful in summarizeing large data set in visual form and we can estimate key values at a glance.

##### 2. What is/are the insight(s) found from the chart?

This bar chart provides us weapon type and deaths caused from each weapon type used major weapon used in attacks were of firearms followed by explosives.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes.. this data will help us to identify the weapon type used in attacks so to keep a strict surveillance on each type and beware of no. Of weapons available in India and take a strong followup of its used and it's smuggling in India.

#### Chart - 16
"""

# Chart - 16 visualization code

# Firearm used vs kills

firearm=data_India.loc[data_India.weaptype1_txt == 'Firearms']
gun_type=firearm.groupby(['weapsubtype1_txt']).agg({'nkill':'sum'})
gun_type.rename(columns={'nkill':'Deaths'},inplace=True)
gun_type.index.names = ['Gun_Type']
gun_type


#Graph

values= gun_type.Deaths
labels= gun_type.index
fig1 = px.pie(gun_type, values=values, names=labels, hole=.5, height = 500, width = 700)
fig1.show()

"""##### 1. Why did you pick the specific chart?

Here we used pie chart because it helps to organize and show data as a percentage of a whole.

##### 2. What is/are the insight(s) found from the chart?

This data gives the type of guns used and death caused by each gun as per chart unknown gun type and automatic or semi automatic rifle is the most used gun type and rifle or shotgun is the least used

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Thi data will help us to identify the gun type used and most dangerous gun and in future we can keep a survilence on this to prevent any such future attack, and also avoid giving licence of this gun.

#### Chart - 17
"""

# Chart - 17 visualization code

# Attack type in India

attack_type=data_India.groupby(['attacktype1_txt']).agg({'nkill':'sum'})
attack_type.rename(columns={'nkill':'Deaths'},inplace=True)
attack_type.index.names = ['attack type']
attack_type


#Graph

attack_type.plot(kind='bar')
plt.xlabel('attack type',fontsize=20)
plt.ylabel('Deaths',fontsize=20)
plt.show

"""##### 1. Why did you pick the specific chart?

As bar graph is helpful in summarizeing large data set in visual form and we can estimate key values at a glance.

##### 2. What is/are the insight(s) found from the chart?

The chart shows the total number of deaths caused by each type of attack in India. From the chart, it can be inferred that the highest number of deaths in India have been caused by bombing/explosion attacks, followed by armed assaults and shootings.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

This information can help the government and security forces to better understand the patterns of terrorist activities and allocate agencies, forces and resources more effectively to counter the threat of terrorism.

#### Chart - 18
"""

# Chart - 18 visualization code

# Target Type India 

target_type=data_India.groupby(['targtype1_txt']).agg({'iyear':'count'})
target_type.rename(columns={'iyear':'No. Of Attacks'},inplace=True)
target_type.index.names = ['Target Type']
target_type


#Graph

target_type.plot(kind='bar', figsize=(16,5))
plt.xlabel('target type',fontsize=20)
plt.ylabel('No. of Attacks',fontsize=20)
plt.show

"""##### 1. Why did you pick the specific chart?

As bar chart show each data category in a frequency distribution, and permit a visual check of the accuracy and reasonableness of calculation it clearly provides the data.

##### 2. What is/are the insight(s) found from the chart?

It provides insights on the most common targets of terror incidents in India and can be useful for governments and law enforcement agencies in improving their security measures to protect those targets.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

It help government and agencies like RAW to better understand the current situation of terrorism in India and allocate resources accordingly by identifying the most targeted type of facilities, they can improve the security measures and prevent terrorist attacks. Additionally, they can also focus their efforts on disabling the operations of specific groups responsible for the majority of attacks on a particular target type. Thus, it can be said that the gained insights can potentially have a positive impact on the government and agencies like RAW.

#### Chart - 19
"""

# Chart - 19 visualization code

#Attack according to lattitude and longitude[India]
attacks_per_lat_long=data_India.groupby(['latitude','longitude']).agg({'iyear':'count'}).reset_index()
attacks_per_lat_long.rename(columns={'iyear':'attacks'},inplace=True)
attacks_per_lat_long.head(5)

#Plotting on map

map1 = fo.Map(location=[data_India.latitude.mean(),data_India.longitude.mean()], zoom_start=5, control_scale=True)
map1

#Plotting Heat map on map

from folium.plugins import HeatMap

HeatMap(attacks_per_lat_long, min_opacity=0.1, blur = 5).add_to(fo.FeatureGroup(name='Heat Map').add_to(map1))
fo.LayerControl().add_to(map1)

map1

"""##### 1. Why did you pick the specific chart?

Here we used folium heatmap because it helps us analyze the location and geospatial data with ease and lets us create interactive maps.

##### 2. What is/are the insight(s) found from the chart?

The heat map shows the concentration of terror attacks in India according to their latitude and longitude. The areas with high concentration of attacks are shown as red, while the areas with low concentration of attacks are shown as blue.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The insights from the chart can help government and agencies like RAW to understand the geographical patterns of terrorist activities in India. Based on this information, they can deploy security forces more effectively in areas where there is a higher likelihood of terrorist attacks. This could lead to a reduction in the number of attacks and a positive business impact for the government and RAW.

#### Chart - 20 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
data_India.corr()

#

corr_matrix = data_India[['iyear','imonth','success','attacktype1','targtype1','guncertain1','weaptype1','nkill','nkillter','ransom']]
corr_matrix = corr_matrix.rename(columns={'iyear': 'Year', 
                                          'imonth': 'Month', 
                                          'success': 'Succesfull attacks', 
                                          'attacktype1': 'Attack Type', 
                                          'targtype1': 'Target Type', 
                                          'guncertain1': 'Type of Gun', 
                                          'weaptype1': 'Weapon Type', 
                                          'nkill': 'No. of Deaths', 
                                          'nkillter': 'No. of Terrorist Deaths', 
                                          'ransom': 'Ransom Demanded'})

#Graph

plt.subplots(figsize=(10, 10))
sns.heatmap(corr_matrix.corr(),cmap='inferno', annot= True)
plt.title('Correlation Metrix for Terrorism Data of India', fontsize= 20)
plt.show()

"""##### 1. Why did you pick the specific chart?

The heatmap was picked to visualize the correlation between different variables in the dataset. The specific variables were chosen as they are commonly used in terrorism studies and they might give some insights into the trends in terrorism in India.

##### 2. What is/are the insight(s) found from the chart?

The insights found from the chart are the correlation between different variables. For example, the correlation between "Year" and "No. of Deaths" is positive and strong, meaning that as the year increases, the number of deaths due to terrorism also increases. Another insight is that there is a weak negative correlation between "Ransom Demanded" and "No. of Deaths", meaning that as the ransom demanded increases, the number of deaths decreases.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The gained insights can help create a positive business impact for government and agencies
like RAW as they can use this information to allocate resources more efficiently and formulate
strategies that focus on areas with high numbers of attacks. The correlation between different 
variables can also help the government to determine what factors may contribute to the increase 
or decrease of terrorism in India and address those factor

# **Conclusion**

Iraq – the country has faced staggering 24636 number of such attacks between 1970 to 2017 which accounted for 13.61% of terrorism attacks in the world.
Attacks were more during 2014 and then in 2015. When compared to attacks from 1970 onwards, the last 6 years scored a maximum. But from 2014 onwards count started decreasing.
Iraq dominates all the countries, and it has the highest number of attacks and then Pakistan, Afghanistan, and India follow it.
Middle East and North Africa and South Asia are the two regions who encountered the greatest number of terror attacks since 1970.
For most of the attacks, the target is Private Citizens & property and the next is on Military leads.
Most of the attacks were through either Bombing or Explosion.
Most used known Attack tactic by terror group is 'Insurgency/Guerrilla Action'. Where the majority of tactic is random or just unknown.
'Islamic State of Iraq and the Levant (ISIL)' were on a killing spree where they murdered 38,793 personal since 1970, Most on compared to other groups. Taliban is again on second place with 29,564 kills.
'Islamic State of Iraq & the Levant (ISIL)' and 'Taliban' are two most active Terrorist groups in the last 5 years.
From Correlation Matrix, We concluded that column elements 'natlty1' and 'country' are have strong relationship which is evident that the Country is most affected by its own population and social disturbances most likely due to Civil war or local terror groups.
Srinagar which is in Jammu and Kashmir has been the centre of the dispute and terror attacks in India.
Seems like Terrorist do like 'Explosives' very much like this is the most used Weapon category across the world terror groups.
Private Citizens and Property related incidents are most common target for Hostage/Kidnapping incidents.
As per analysis, You have about 22.18% chance to get out of kidnapping situation without any hard, but 18.46% bad luck that you won't.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""